### ISSUE TITLE
Check compatibility with Split v1.1.0

### ISSUE THREAD

**Issue by andrew** [bernardkroes/split-counters#2]
Just a heads up really, yesterday I released [v1.1.0](https://github.com/andrew/split/releases/tag/v1.1.0) of Split which included some [internal refactoring](https://github.com/andrew/split/pull/286) that you may rely on in this extension so you may want to check that it's not broken anything.

**Comment by bernardkroes** [comment]
Upgraded and ran the tests. All passing.

**Comment by andrew** [comment]
Great! Thanks @bernardkroes
